# -*- coding: utf-8 -*-
"""cie3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WE5vf-c67ItEr0EwZD5tnqrFjFR9n_TF
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import  train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

data= fetch_california_housing()
data

df = pd.DataFrame(data.data, columns=data.feature_names)
df['price']=data.target
print(df)

df.describe()

df.info()

x = df.drop('price', axis=1)
y = df['price']
x
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train
y_train

x_test
y_test

model=LinearRegression()
model.fit(x_train,y_train)

yprd=model.predict(x_test)
yprd

mse=mean_squared_error(y_test,yprd)
mse

rscore=r2_score(y_test,yprd)
rscore